### ISSUE TITLE
Discord integration: "Unable to find acceptable protocols"

### ISSUE THREAD

**Issue by rieling** [yummypasta/MinecraftManhunt#57]
An internal error occurred while attempting to perform this command.

Ive been getting this message on all commands ever since i connected discord up to the music.

[09:01:32 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'speedrunner' in plugin MinecraftManhunt v1.3.3.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.16.5.jar:git-Paper-439]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2021) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1832) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1785) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1132) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1125) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1086) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1000) ~[patched_1.16.5.jar:git-Paper-439]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-439]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.IllegalArgumentException: Role may not be null
        at net.dv8tion.jda.internal.utils.Checks.notNull(Checks.java:64) ~[?:?]
        at net.dv8tion.jda.internal.entities.GuildImpl.addRoleToMember(GuildImpl.java:1205) ~[?:?]
        at com.yoonicode.minecraftmanhunt.DiscordManager.assignRole(DiscordManager.java:128) ~[?:?]
        at com.yoonicode.minecraftmanhunt.PluginCommands.onCommand(PluginCommands.java:195) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Paper-439]
        ... 19 more

this is my error code when trying to make someone a speedrunner

**Comment by yummypasta** [comment]
Thanks for submitting this issue! Looking at your logs, I can see a few things that may be causing this bug...
- Please make sure all of your Discord Role IDs in config.yml are correct— for hunter, speedrunner, and spectator. If you don't need automatic role assignment, you can delete the three fields.
- Make sure your Discord bot has administrator permissions in your server, and its highest role is above your hunter, speedrunner, and spectator roles.
- Make sure your server's system clock is set to the correct time; if it is too off, network requests will be rejected.

If none of these fixes work, please upload your plugin config.yml file and I can further assist you!

**Comment by rieling** [comment]
what if i have more then one hunter

**Comment by yummypasta** [comment]
That shouldn't cause any issues. If the fixes above didn't work, can you pleaseu pload your config.yml file, which should be found in `plugins/MinecraftManhunt/config.yml`?
