### ISSUE TITLE
An Internal Error Occurred While Attempting to perform this command

### ISSUE THREAD

**Issue by GamerToTheMax** [yummypasta/MinecraftManhunt#70]
## Describe the bug
So Im trying to Run the Speedrunner, Hunter and Spectator commands but they both spit out internal errors when being run
## Potential Causes
Im not sure Ive enabled And intergrated the discord bot i made into my discord server but other then that im not sure

## Environment Info
Plugin version 1.4

Paper 279

## Configuration file

# How long the hunters should get blindness and slowness when the match starts.
headStartDuration: 0
compassEnabledInNether: true
sendUsageData: true
huntersColor: '&c'
runnersColor: '&a'
spectatorsColor: '&b'
setRunnersToSpecOnDeath: true
clearRunnerInvOnStart: true
clearHunterInvOnStart: true
clearItemDropsOnStart: true
setTimeToZero: true
startGameByHit: true
preGameWorldBorder: false
preGameBorderSize: 100
enableDiscord: true
discordToken: (REDACTED)
ip:( My public Ip)
processDiscordCommands: true
discordServerId: 894138460938596362
musicChannelId: 894138461685157891
hunterRoleId: 894138799733473280
runnerRoleId: 894139005665427466
spectatorRoleId: 894139071042052136
uuid: 7bf0b72b-2273-4367-b7f6-820048c6c6af

## Server Logs
Please check your Server Console for any warnings or errors created by the plugin. If any are any, please copy and paste them here:
Paste relevant console warnings/errors here
[08:03:11 INFO]: [MinecraftManhunt] Assigning role RUNNER to GamerToTheMax
[08:03:12 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'speedrunner' in plugin MinecraftManhunt v1.3.3.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-279]
        at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:838) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2257) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2068) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2049) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:46) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.network.protocol.game.PacketPlayInChat.a(PacketPlayInChat.java:6) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:56) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:149) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.executeTask(IAsyncTaskHandlerReentrant.java:23) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:1418) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.executeTask(MinecraftServer.java:192) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:122) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.bf(MinecraftServer.java:1396) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.executeNext(MinecraftServer.java:1389) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.util.thread.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:110) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1528) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1274) ~[patched_1.17.1.jar:git-Paper-279]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-279]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: net.dv8tion.jda.api.exceptions.HierarchyException: Can't modify a role with higher or equal highest role than yourself! Role: R:Runner(894139005665427466)
        at net.dv8tion.jda.internal.entities.GuildImpl.checkPosition(GuildImpl.java:1492) ~[MinecraftManhunt-1.4.jar:?]
        at net.dv8tion.jda.internal.entities.GuildImpl.addRoleToMember(GuildImpl.java:1226) ~[MinecraftManhunt-1.4.jar:?]
        at com.yoonicode.minecraftmanhunt.DiscordManager.assignRole(DiscordManager.java:128) ~[MinecraftManhunt-1.4.jar:?]
        at com.yoonicode.minecraftmanhunt.PluginCommands.onCommand(PluginCommands.java:206) ~[MinecraftManhunt-1.4.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.17.1.jar:git-Paper-279]
        ... 21 more

![Screenshot (68)](https://user-images.githubusercontent.com/64049817/135771940-52ba22b6-436a-439b-b047-e637bda19ce3.png)

**Comment by Creeperboy102** [comment]
Ive Also tried running the commands straight from the console but it gives the same error

**Comment by GamerToTheMax** [comment]
Ok ive messed around in the config file and it seems that enableDiscord Is the thing thats triggering it

**Comment by yummypasta** [comment]
Hi, thanks for using the plugin. Thanks for providing logs and your config—I'll look into the issue. For now, you might be able to fix the issue by omitting your discord role IDs, which will disable the role assignment feature and you might be able to get the bot to work.

**Comment by GamerToTheMax** [comment]
Ok ill try that and ill let you know how it goes

**Comment by GamerToTheMax** [comment]
Ok That seems to have worked for now. Ima keep using this because all the other features are amazing

**Comment by GamerToTheMax** [comment]
@yummypasta I actually know whats causing this. In discord the roles can be ordered from highest to lowest and the auto assigned roles were at the top and the bot was below so im pretty sure the bot wasnt able to access the higher roles so i moved the bot role to the top and its working with the auto roles so yea it wasnt the plugin its just you have to but the bot role on top of the others

**Comment by GamerToTheMax** [comment]
![Screenshot (75)](https://user-images.githubusercontent.com/64049817/135942387-49778720-1e8c-4aec-a11c-1fa0b6911039.png)

As you can see The Role the bot has needs to be at the top or above the  in game team  roles. Otherwise it gives an internal error when trying to run a team command

**Comment by yummypasta** [comment]
Glad you could resolve the issue!
